# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DnD' do
  pod 'SwiftLint', '0.31.0'
  use_frameworks!

  # Pods for DnD

  target 'DnDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DnDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
